### ISSUE TITLE
Command Line?

### ISSUE THREAD

**Issue by Doxmiatoo** [theRealCarneiro/pulsemeeter#15]
Any chance for command line arguments to toggle things to be able to keybind or macro certain things? ie: toggle A2 on Virtual Input 1, things like that.

Thanks for making this!

**Comment by theRealCarneiro** [comment]
You can already do this, I didn't include in the documentation because I plan on changing this, but this is how it works now:
`pulsemeeter [connect|disconnect] [vi|hi] NUMBER [a|b] NUMBER`
`pulsemeeter eq [activate|remove] [a|b] NUMBER`
`pulsemeeter mute [hi|vi|a|b]`

For volume you can use `pactl`

**Comment by Doxmiatoo** [comment]
Ah awesome! I'll use that for now, then. Can I suggest adding a toggle as well? (if off then turn on, if on then turn off). Thank you!

**Comment by Doxmiatoo** [comment]
Hmmn, mute or disconnect doesn't seem to be doing anything... if I have the actual interface open does that interfere?

**Comment by Fl1tzi** [comment]
Hey, I want to implement it into my elgato stream deck (like @Doxmiatoo mentioned a toggle) and to retrieve the status of a device, etc... Is there already a way to do these things in the CLI or are you going to extend the API (to use for example in Python)?

**Comment by theRealCarneiro** [comment]
> Hmmn, mute or disconnect doesn't seem to be doing anything... 
Taking a quick look I didn't have any issues with them, but I'll run more tests

> if I have the actual interface open does that interfere?
If the interface is open it will override the config file for whatever settings are there, but it wont affect the command being run

**Comment by theRealCarneiro** [comment]
>  Is there already a way to do these things in the CLI or are you going to extend the API

Not yet, but I'm working on a better cli interface + daemon mode and that will surely be included, for now you could write a python script that reads the configuration file (it's just a json)
