### ISSUE TITLE
Q: volume normalize using swh-plugins

### ISSUE THREAD

**Issue by atomGit** [theRealCarneiro/pulsemeeter#18]
i see we can apparently load swh-plugins - would it be possible to use swh-plugins to normalize volume?

i'm using pipewire on manjaro (kde) with the helvum patchbay - i assume i would need to replace helvum with pulsemeter?

what i'm wanting to accomplish is to have a volume normalize sync that i can switch to using the volume control applet provided by plasma-pa

**Comment by theRealCarneiro** [comment]
In the latest version on the main branch you can now set an "external: [true|false]" key in the config, enabling you to use any output device (hardware outputs, null sinks, ladspa sinks, pipewire sinks) as a virtual input, thus enabling you to setup plugins externally and let pulsemeeter handle the usual connections

> what i'm wanting to accomplish is to have a volume normalize sync that i can switch to using the volume control applet provided by plasma-pa

pulse is very strict with plugins control values, I think that's not possible
