### ISSUE TITLE
Virtual Sink Persistence

### ISSUE THREAD

**Issue by hugeblank** [theRealCarneiro/pulsemeeter#3]
I'd like to have the virtual sinks be present on startup. As of right now there doesn't seem to be a way to do that, aside from starting pulsemeeter. I like the way voicemeeter does this, it starts hidden and in the taskbar, no popups or anything like that. However pulseaudio has a method of creating sources and sinks when it gets initialized (I believe it's adding to `~/.config/pulse/default.pa` but I may be wrong). Maybe pulsemeeter could utilize that, and not have to be start up at all?

**Comment by theRealCarneiro** [comment]
just run `pulsemeeter init`, forgot to add that to the wiki and readme

**Comment by hugeblank** [comment]
oh sweet! glad this was already implemented
