### ISSUE TITLE
Clarification of how virtual outputs are presented

### ISSUE THREAD

**Issue by hugeblank** [theRealCarneiro/pulsemeeter#4]
I have a question regarding virtual outputs (B1-3). What are they and how are they presented? I can't find how they're represented in pulseaudio. I assumed they were Mic/Mic_Aux/Mic_Aux_2 but that doesn't make much sense given the naming scheme for the virtual inputs (Virtual_Sink/_Aux/_Aux_2). What I'd expect to see are 3 sources named in the same way (Virtual_Source/_Aux/_Aux_2), but they don't seem to exist.

![image](https://user-images.githubusercontent.com/16393543/141265578-446ae6ab-6237-4d1a-855e-d7c5bee3f5d3.png)
For less savvy users, I'm asking about the right side box labelled Virtual Outputs.

Loving the consistent addition of features to pulsemeeter, it's really impressive!

**Comment by theRealCarneiro** [comment]
> I assumed they were Mic/Mic_Aux/Mic_Aux_2


You're correct, I'm just bad at naming things. I did't give much thought into naming since you can just rename them (you can rename virtual inputs in the app, but virtual outputs you need to change it directly in the config file in .config/pulsemeeter/config.json, next patch I'll make so that you can rename them it the app too), but I should probably change it to one that makes more sense.

I can think of two different aproches as how to have a good default name: Change it to Virtual_Output_[1..3] or a maybe just B[1..2], what do you think?

> Loving the consistent addition of features to pulsemeeter, it's really impressive!

Thank you, I really enjoy developing this app

**Comment by hugeblank** [comment]
> I can think of two different approaches as how to have a good default name: Change it to Virtual_Output_[1..3] or a maybe just B[1..2], what do you think?

I kinda like the idea of combining both suggestions: `Mic_Aux` set becomes `Virtual_Output_B[1..3]`, and while we're changing default names, the current `Virtual_Sink` set could make more sense as `Virtual_Input_[1..3]`.

> Thank you, I really enjoy developing this app

This is really good to hear! If you ever feel in the mood to go extreme GUI, I think it'd be cool to have a setup where sinks and sources (of hardware, virtual, and loopback) were all represented on a canvas, where the user could drag and drop them, connecting virtual cables between them. But that's tangential to this discussion, and definitely a v2.0 or even later thing.

**Comment by theRealCarneiro** [comment]
> I kinda like the idea of combining both suggestions: Mic_Aux set becomes Virtual_Output_B[1..3], and while we're changing default names, the current Virtual_Sink set could make more sense as Virtual_Input_[1..3].

I like that ideia, just pushed an update for that (also featuring volume meters).

> I think it'd be cool to have a setup where sinks and sources (of hardware, virtual, and loopback) were all represented on a canvas, where the user could drag and drop them, connecting virtual cables between them

I thought about that, but the ideia of this app is to look and feel similar to voicemeeter, doing that would ruin that aspect. I think it's a better ideia to develop another app for that, maybe in the near future I'll start working on that ideia.
