### ISSUE TITLE
[Bug] data loss when not closing Pulsemeeter properly

### ISSUE THREAD

**Issue by Fl1tzi** [theRealCarneiro/pulsemeeter#56]
**Is your feature request related to a problem? Please describe.**
Currently the config gets saved when exiting Pulsemeeter properly and that leads to data loss when not closing Pulsemeeter before shutting down. This means we need a way to write the config when changes are made.

**Describe the solution you'd like**
When a change is made in Pulsemeeter it should wait for about 20 seconds if they are more changes made (reset the timer when another change is made). Then we could save the config and then Pulsemeeter would not take up huge amounts of ressources and would also only save when needed. This would fix the data loss.

**Describe alternatives you've considered**
Currently none but probably saving on shutdown would be possible but would not protect against crashes and other things.

**Additional context**
~~Maybe the volume and mute state could get removed from the config as we could use the data from pulseaudio (maybe could improve performance).~~

**Comment by snoweuph** [comment]
I wouldn't remove the Volume, because for me pulse itself sometimes loses the volume settings completely. I got this problem on multiple devices running clean installations of Mint, so It can't be just some weird config I did.

**Comment by Fl1tzi** [comment]
Fixed in pipewire branch.
