### ISSUE TITLE
pulsemeeter init not setting default device

### ISSUE THREAD

**Issue by Uronic** [theRealCarneiro/pulsemeeter#6]
On startup, pulsemeeter makes the virtual devices but doesn't set them as default.

**Comment by theRealCarneiro** [comment]
Hey there, are you using pulseaudio or pipewire? Pulseaudio was supposed to remember the default devices and load them as soon as it detects them. That could also be a settings that I put in my pulseaudio configuration and can't remember, can you confirm if `pulseaudio.socket` is enabled and running on systemd(`systemctl --user status pulseaudio.socket`)? I can easily fix that on the code, but i assumed pulseaudio would restore the defaults anyone like it does on my machine

**Comment by Uronic** [comment]
pulseaudio.socket is enabled. Maybe you have modules enabled in pulseaudio that I don't have enabled?

**Comment by theRealCarneiro** [comment]
In `/etc/pulse/default.pa` there's `load-module module-default-device-restore`, but I don't remember putting that there, so it's probably there by default, It's probably best if I ensure that in the application rather than relying on pulse to do all that
