### ISSUE TITLE
High memory usage when application is in the background.

### ISSUE THREAD

**Issue by sharifhsn** [theRealCarneiro/pulsemeeter#63]
**Describe the bug**
Over time, the application slowly grows in memory usage despite not doing anything. It starts at about 80 MB when opening, but over time can grow up to 5 or 6 GB of memory. Terminating the application and reopening it solves this issue without any apparent change.

**To Reproduce**
1. Open application
2. Leave it running for some time
3. Check memory usage

**Expected behavior**
I expect the memory usage to remain the same over time, which is around 80 MB on my system at startup.

**Desktop (please complete the following information):**
 - Distro: Arch
 - Python Version: 3.10.5

**Comment by Fl1tzi** [comment]
Hello,
Could you specify what „some time“ means? Does it take about an hour? 15 mins?

**Comment by Seraphli** [comment]
![image](https://user-images.githubusercontent.com/1586755/202862485-f4910032-9e99-4d53-a050-673be48c4236.png)
I also observe memory growth. My OS is manjaro. I don't know when it starts to grow. Perhaps the growth began when I fed sound into virtual input. The total time adds up to about 3 hours I guess.
