### ISSUE TITLE
[BUG] ValueError: Namespace AppIndicator3 not available

### ISSUE THREAD

**Issue by fallowmcolstein** [theRealCarneiro/pulsemeeter#66]
when I try to run pulsemeeter (installed with: `sudo pip install pulsmeeter` on Pop!_OS 22.04, with python 3.10.4, it doesn't open. When I run it in the terminal it says: 
Traceback (most recent call last):
  File "/usr/local/bin/pulsemeeter", line 5, in <module>
    from pulsemeeter.__main__ import main
  File "/usr/local/lib/python3.10/dist-packages/pulsemeeter/__init__.py", line 1, in <module>
    from .interface import MainWindow
  File "/usr/local/lib/python3.10/dist-packages/pulsemeeter/interface/__init__.py", line 2, in <module>
    from .main_window import MainWindow
  File "/usr/local/lib/python3.10/dist-packages/pulsemeeter/interface/main_window.py", line 26, in <module>
    gi_require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

**Comment by Fl1tzi** [comment]
Hello. You are missing the libappindicator of your distro. You should be able to install it by writing `sudo apt install libappindicator-dev` in your terminal. If that didn't work for you or you need more help, you might be interested in joining our Discord: https://discord.gg/ekWt9NuEWv . Closing this issue because it isn't an issue with the software.

**Comment by Josef-Reichardt** [comment]
Same error on Ubuntu 22.04 LTS. Installing `libappindicator-dev` does not help:

```
Traceback (most recent call last):
  File "/home/reichardt/.local/bin/pulsemeeter", line 5, in <module>
    from pulsemeeter.__main__ import main
  File "/home/reichardt/.local/lib/python3.10/site-packages/pulsemeeter/__init__.py", line 1, in <module>
    from .interface import MainWindow
  File "/home/reichardt/.local/lib/python3.10/site-packages/pulsemeeter/interface/__init__.py", line 2, in <module>
    from .main_window import MainWindow
  File "/home/reichardt/.local/lib/python3.10/site-packages/pulsemeeter/interface/main_window.py", line 26, in <module>
    gi_require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

I think the according package for this OS would be `libayatana-appindicator3-dev`? But unfortunately it doesn't solve the issue.

**Comment by Fl1tzi** [comment]
Unkle Bonehead seems to have posted a solution on our Discord:

(8.6.2022)
`sudo apt install gir1.2-appindicator3-0.1`

Please confirm if it worked so we can put it in our install instructions.

**Comment by ZerkerEOD** [comment]
@Fl1tzi I was just having the same error and installing `gir1.2-appindicator3-0.1` fixed that issue for me. I am running Kali though so I had to manually install as the repo does not include that package. I am going to look through the rest of the issues though to see if I can find my new one to keep from hijacking another thread.

To answer the question, I think adding that to the install instructions may be a good idea as it got rid of the error for me.

**Comment by Josef-Reichardt** [comment]
Installing `gir1.2-appindicator3-0.1` works on Ubuntu 22.04 LTS. :+1: 

(sry for the late reply)

**Comment by KaKi87** [comment]
Hello,

I experienced the following error when trying to install the `libappindicator3-dev` package :
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libayatana-appindicator3-1 : Conflicts: libappindicator3-1
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```
Trying to install `gir1.2-appindicator3-0.1` instead solved the issue.
Could please the wiki be updated accordingly ?

Also the `Ubuntu (apt based)` item of the table of contents doesn't work.

Thanks

**Comment by giuspal68** [comment]
No way to solve it on debian 12?file:///home/giuseppe/Immagini/Schermate/Schermata%20del%202023-06-28%2021-26-08.png

**Comment by PaperShreds** [comment]
can't install gir1.2-appindicator3-0.1

"Package 'gir1.2-appindicator3-0.1' has no installation candidate"
what do i do? tried everything

**Comment by ZerkerEOD** [comment]
You would need to look into what your distribution packages it as.

**Comment by sblmnl** [comment]
> No way to solve it on debian 12?file:///home/giuseppe/Immagini/Schermate/Schermata%20del%202023-06-28%2021-26-08.png

> can't install gir1.2-appindicator3-0.1
> 
> "Package 'gir1.2-appindicator3-0.1' has no installation candidate" what do i do? tried everything

if you're on debian (amd64) run:
```
ARCH=amd64
curl http://ftp.us.debian.org/debian/pool/main/liba/libappindicator/gir1.2-appindicator3-0.1_0.4.92-7_$ARCH.deb \
    -o gir1.2-appindicator3-0.1.deb && sudo dpkg -i gir1.2-appindicator3-0.1.deb
rm gir1.2-appindicator3-0.1.deb
```

if that doesn't work initially, try:
`sudo apt --fix-broken install`
