### ISSUE TITLE
No audio routed to/from any virtual inputs/outputs using pipewire

### ISSUE THREAD

**Issue by dacid44** [theRealCarneiro/pulsemeeter#7]
As soon as I launch pulsemeeter, all audio gets routed there. However, there are two problems: The applications' audio doesn't seem to get connected to the meters, and the audio doesn't seem to get routed properly from the "Virtual Inputs" to the hardware outputs. (It doesn't look like any of the "Virtual Inputs" or "Virtual Outputs" are working at all, actually. The only working pathway through the application, tested using a patchbay to connect things where they probably weren't intended, is from a "Hardware Input" to a "Hardware Output"). I'd be happy to provide more info or otherwise help resolve this, as Pulsemeeter looks like it would be ideal for me, if only it worked with the rest of my setup.

(I'm on version 1.2.6, other possibly relevant info: pipewire, pipewire-alsa, pipewire-pulse, pipewire-jack, and pulseaudio-alsa are all installed. I'm running Arch Linux (pulsemeeter installed from the AUR) and Cinnamon.)

Thanks!

**Comment by s1011205** [comment]
Does this problem mean that if I am thinking of switching to Fedora, which uses Pipewire as default, pulsemeeter would not work? If so, is there any idea of when it would work with Pipewire on Fedora?

**Comment by theRealCarneiro** [comment]
It works on fedora with pipewire, @dacid44 has a very specific build on his Arch system that for reason conflicts with pulsemeeter, for the rest of the pipewire users it will work

**Comment by s1011205** [comment]
That's great! Thank you for all the work you have done on this, Gabriel. It's one of the areas that Linux was lacking an important piece of software, and assuming further development that improves it even more, this piece of software would fill that gap.

**Comment by theRealCarneiro** [comment]
Pipewire version is now available in the [nightly](https://github.com/theRealCarneiro/pulsemeeter#nightly) branch
