### ISSUE TITLE
AUR packages don't build anymore

### ISSUE THREAD

**Issue by ayush123460** [theRealCarneiro/pulsemeeter#9]
AUR packages don't build anymore citing `ERROR: pulsectl not installed, please run 'pip install requirements.txt' inside source directory`. Please let me know if you need more details.

**Comment by theRealCarneiro** [comment]
Reinstall python-pulsectl and it should work

**Comment by ayush123460** [comment]
Have just tried, it did not work.

**Comment by theRealCarneiro** [comment]
Did you do a clean reinstall?

**Comment by theRealCarneiro** [comment]
I did some testing, this issue happens because python updated to 3.10 on arch, and pulsectl is installed in an old directory, to fix this you need to delete your aur helper cache for python-pulsectl and reinstall it

**Comment by ayush123460** [comment]
Hey, what do you know! That worked. Due to an unknown reason my paru cache dir had it's permissions wrong and couldn't delete. Fixed that, ran `paru -Scc`, removed `python-pulsectl`, and reinstalled `pulsemeeter-git` and it worked! Thank you for your time, I have been missing pulsemeeter since it broke trying to update :heart:

**Comment by theRealCarneiro** [comment]
Glad to hear everything is working out
