### ISSUE TITLE
Daemon doesn't start properly when using pipewire-pulse

### ISSUE THREAD

**Issue by M3gaFr3ak** [theRealCarneiro/pulsemeeter#95]
**Describe the bug**
When pulsemeeter is started using the daemon option after starting pipewire-pulse, it gives me the following error and doesn't work:
```
Error setting sink Virtual_Input_1 as primary
Error setting source Virtual_Output_B1 as primary
```

Error on the pipewire-pulse side (using `systemctl --user status pipewire-pulse.service`):

```
Aug 29 11:12:59 ZephyrusLeon pipewire-pulse[48052]: mod.loopback: error id:0 seq:91 res:-32 (Broken pipe): connection error
Aug 29 11:12:59 ZephyrusLeon pipewire-pulse[48052]: mod.loopback: error id:0 seq:80 res:-32 (Broken pipe): connection error
Aug 29 11:12:59 ZephyrusLeon pipewire-pulse[48052]: mod.null-sink: error id:0 seq:51 res:-32 (Broken pipe): connection error
Aug 29 11:12:59 ZephyrusLeon pipewire-pulse[48052]: mod.loopback: error id:0 seq:101 res:-32 (Broken pipe): connection error
Aug 29 11:12:59 ZephyrusLeon pipewire-pulse[48052]: mod.null-sink: error id:0 seq:72 res:-32 (Broken pipe): connection error
Aug 29 11:12:59 ZephyrusLeon pipewire-pulse[48052]: mod.loopback: error id:0 seq:140 res:-32 (Broken pipe): connection error
Aug 29 11:12:59 ZephyrusLeon pipewire-pulse[48052]: mod.null-sink: error id:0 seq:93 res:-32 (Broken pipe): connection error
Aug 29 11:12:59 ZephyrusLeon pipewire-pulse[48052]: mod.null-sink: error id:0 seq:102 res:-32 (Broken pipe): connection error
Aug 29 11:12:59 ZephyrusLeon pipewire-pulse[48052]: mod.null-sink: error id:0 seq:111 res:-32 (Broken pipe): connection error
Aug 29 11:12:59 ZephyrusLeon pipewire-pulse[48052]: mod.null-sink: error id:0 seq:121 res:-32 (Broken pipe): connection error
```

**To Reproduce**
1. Stop pipewire-pulse.socket and pipewire-pulse.service.
2. Start pipe-wirepulse again.
3. execute `pulsemeeter daemon`.
The `-d` option doesn't print any further errors.

**Workaround?**
There are two ways of running pulsemeeter properly:

Method 1:
1. Stop pipewire-pulse.socket and pipewire-pulse.service.
2. Start pipe-wirepulse again.
3. execute `pulsemeeter` (without `daemon`).

Method 2:
1. Stop pipewire-pulse.socket and pipewire-pulse.service.
2. Start pipe-wirepulse again.
3. Start PulseAudio Volume Control.
5. Execute `pulsemeeter daemon`.
6. You may now quit PAVU.

**Expected behavior**
Pulsemeeter should, as a daemon, also launch properly and not cause errors.

**Desktop (please complete the following information):**
 - Distro: EndeavourOS Linux x86_64
 - Kernel: 5.18.16-arch1-g14-2
 - Python 3.10.6

**Comment by serossi** [comment]
that is known and not implemented yet, there is a branch for pipewire pulse, dunno how functional
looking at the current state of branches i would say patience, patience, patience

seems like he try to implement socket, pipewire while doing an ui refactor. so i would expect a merged release somewhere nextg spring

**Comment by Fl1tzi** [comment]
> that is known and not implemented yet, there is a branch for pipewire pulse, dunno how functional
> 
> looking at the current state of branches i would say patience, patience, patience
> 
> 
> 
> seems like he try to implement socket, pipewire while doing an ui refactor. so i would expect a merged release somewhere nextg spring

There is a nightly branch you can try out which should work much better for pipewire. Guide is on the wiki.

**Comment by M3gaFr3ak** [comment]
The nightly branch works properly, thank you!

Closing as it's working in a future version.
