### ISSUE TITLE
Problem when start pulsemeeter

### ISSUE THREAD

**Issue by kureshio** [theRealCarneiro/pulsemeeter#97]
I installed pulsemeeter, when I open it, it shows the error below.

[kureshio@linux-casa ~]$ pulsemeeter
ERROR: invalid json grep: warning: stray \ before #
grep: warning: stray \ before #
grep: warning: stray \ before #

invalid json from server
App sinks returned an error, audio backend probably crashed. Server will be closed.
Could not join subscribe_thread (maybe there is none)
closing client handler threads...
closing socket
sending exit signal to listener thread, it should exit within 2 seconds...

Pulseaudio is installed.

Distro: Archlinux

**Comment by doubledge-spec** [comment]
same/similar issue
`$ pulsemeeter
Could not start vumeter for Virtual_Input_3
invalid json from server
App sinks returned an error, audio backend probably crashed. Server will be closed.
Could not join subscribe_thread (maybe there is none)
closing socket

(pulsemeeter:116154): Gtk-CRITICAL **: 02:58:00.856: gtk_main_quit: assertion 'main_loops != NULL' failed`

**Comment by Fl1tzi** [comment]
#59

This is an issue we have in the older version. If you are running pulseaudio/pulseaudio over version 16 it is fixed in the nightly version. The guide on how to install is on https://github.com/theRealCarneiro/pulsemeeter/wiki/Installation#Nightly-installationupdate-script .
